"""
Created on 14/01/2019
@author: nidragedd

Constants file
"""

MODEL_RANDOMFOREST = 'rf'
MODEL_NEURALNETWORK = 'nn'
MODEL_XGBOOST = 'xgb'

ALLOWED_MODELS = [MODEL_RANDOMFOREST, MODEL_NEURALNETWORK, MODEL_XGBOOST]
NORMALIZATION_MODEL = [MODEL_NEURALNETWORK, MODEL_XGBOOST]

OBJECTIVE_OPTIONS = ['prepare', 'predict', 'both']